# mosdns service install -d working_dir_absolute_path -c config_path
# mosdns service start
# mosdns service stop
# mosdns service uninstall

log:
  level: info # 日志级别 info / warning / error / debug，默认 info
  file: './mosdns.log' 

##################################################
include:                         # 外部配置优先初始化
  - './config_matcher.yaml'      # 请求应答匹配配置
  - './config_forward.yaml'      # 请求转发配置
  - './config_etc.yaml'          # 其他配置
  - './config_sequence.yaml'     # 执行序列配置

data_providers:                  # 数据源配置
  - tag: 'forged_IPv4'           # 已知污染 IP
    file: './forged_IPv4_20200828.txt' 
  - tag: 'oisd'                  # OISD
    file: './oisd_dblw_full.txt' 
  - tag: 'direct-list'           # GeoSite-direct
    file: './direct-list.txt' 
  - tag: 'geosite'               # GeoSite
    file: './geosite.dat' 
  - tag: 'geoip'                 # GeoIP
    file: './geoip.dat'     

##################################################
servers:                         # 服务器配置
  - exec: 'sequence_main'        # 主执行序列
    timeout: 5                   # 请求处理超时时间（s），默认 5
    listeners: 
      - protocol: udp
        addr: 127.0.0.1:53
      - protocol: tcp
        addr: 127.0.0.1:53
      - protocol: udp
        addr: '[::1]:53'
      - protocol: tcp
        addr: '[::1]:53'
api:                           # API 配置
  http: '127.0.0.1:8080'       # API 访问地址