# hosts                          # 域名映射
# ecs_mainland                   # 请求来源覆盖
# ttl                            # 应答生存 300 ~ 1500（ms）

plugins:
##################################################
  - tag: 'hosts'                 # 域名映射
    type: 'hosts' 
    args: 
      hosts: # 顺序初始化，相同域名时，前排将会被后排覆盖
        - 'full:dot.pub 1.12.12.12 120.53.53.53' # DNSPod
        - 'full:dns.alidns.com 223.5.5.5 223.6.6.6' # AliDNS
        - 'full:dns.twnic.tw 101.101.101.101 101.102.103.104' # Quad 101 DNS
        - 'full:public.dns.iij.jp 103.2.57.5 103.2.57.6' # IIJ DNS

##################################################
  - tag: 'ecs_mainland'          # 请求来源覆盖
    type: 'ecs' 
    args: 
      auto: false 
      ipv4: '210.21.196.6'       # 广东联通
      force_overwrite: true      # 强制覆盖启用
      mask4: 24 

##################################################
  - tag: 'ttl'                   # 应答生存 300 ~ 1500（ms）
    type: 'ttl' 
    args: 
      minimal_ttl: 300
      maximum_ttl: 1500