# matcher_extra_domain           # 匹配特殊域名请求
# exclude_ad_domain              # 排除广告域名请求
# matcher_ad_domain              # 匹配广告域名请求
# exclude_mainland_domain        # 排除大陆域名请求
# matcher_mainland_domain        # 匹配大陆域名请求
# matcher_oversea_domain         # 匹配境外域名请求
# exclude_mainland_ip            # 排除大陆 IP 应答
# matcher_mainland_ip            # 匹配大陆 IP 应答

plugins:
  - tag: 'matcher_extra_domain'  # 匹配特殊域名请求
    type: 'query_matcher'
    args: 
      domain:

  - tag: 'exclude_ad_domain'     # 排除广告域名请求
    type: 'query_matcher'
    args:
      domain:

  - tag: 'matcher_ad_domain'     # 匹配广告域名请求
    type: 'query_matcher'
    args:
      domain:
        - 'provider:oisd'        # oisd 域名表

  - tag: 'exclude_mainland_domain' # 排除大陆域名请求
    type: 'query_matcher'
    args:
      domain:

  - tag: 'matcher_mainland_domain' # 匹配大陆域名请求
    type: 'query_matcher'
    args:
      domain:
        - 'domain:deepl.com'     # deepL translater
        # CN 类域名
        - 'provider:geosite:cn,apple-cn,amazon@cn,google-cn,category-bank-cn,category-games@cn,category-media-cn,microsoft@cn,category-mooc-cn,category-securities-cn,category-wiki-cn'

  - tag: 'matcher_oversea_domain' # 匹配境外域名请求
    type: 'query_matcher'
    args:
      domain:
        - 'provider:geosite:geolocation-!cn' # 非 CN 类域名

  - tag: 'exclude_mainland_ip'   # 排除大陆 IP 应答
    type: response_matcher
    args:
      ip:
        - 'provider:forged_IPv4' # 已知污染 IP

  - tag: 'matcher_mainland_ip'   # 匹配大陆 IP 应答
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'    # CN 类 IP
