# mosdns service install -d working_dir_absolute_path -c config_path
# mosdns service start
# mosdns service stop
# mosdns service uninstall

log:
  level: warn # 日志级别 info / warn / error / debug，默认 info
  file: './mosdns.log' 

include:
  - './config_matcher.yaml'      # 请求应答匹配配置
  - './config_forward.yaml'      # 请求转发配置
  - './config_etc.yaml'          # 其他配置
  - './config_sequence.yaml'     # 执行序列配置

data_providers:
  - tag: 'forged_IPv4'           # 已知污染 IP
    file: './forged_IPv4_20220803.txt' 
  - tag: 'oisd'                  # OISD Domain
    file: './oisd_dblw_full.txt' 
  - tag: 'geosite'               # GeoSite
    file: './geosite.dat' 
  - tag: 'geoip'                 # GeoIP
    file: './geoip.dat'     

servers:
  - exec: 'sequence_main'        # 主执行序列
    timeout: 5
    listeners:
      - protocol: udp
        addr: 127.0.0.1:53
      - protocol: tcp
        addr: 127.0.0.1:53
      - protocol: udp
        addr: '[::1]:53'
      - protocol: tcp
        addr: '[::1]:53'

api:
  http: '127.0.0.1:8080'
